version: "3"
services:
  frjns_db:
    image: mysql
    environment:
      MYSQL_DATABASE: frjns
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    container_name: frjns_db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - "frjns_db_volume:/Users/hanhyunsoo/dev/volumes/frjns"
    restart: on-failure
    ports:
      - "3306:3306"

volumes:
  frjns_db_volume: