cors:
  allowed-origins: "*"

---
# ?? ??
spring:
  # ??? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frjns
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: jdbc:mysql://localhost:3306/frjns
      username: ${LOCAL_DB_USERNAME}
      password: ${LOCAL_DB_PASSWORD}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  # JPA ??
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
  config:
    activate:
      on-profile: development

logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug
        orm:
          jdbc:
            bind: trace

---

# ?? ??
spring:
  # ??? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_JDBC_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${RDS_JDBC_URL}
      username: ${RDS_USERNAME}
      password: ${RDS_PASSWORD}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  # JPA ??
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
  config:
    activate:
      on-profile: production
  devtools:
    livereload:
      enabled: off

server:
  error:
    include-stacktrace: never